version: '3.6'
services:
  my-nginx:
    build:
      context: ./my-nginx/
      args:
        ENABLED_MODULES: cachepurge
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./my-nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - image-store
    networks:
      - backend

  image-store:
    image: nginx:latest
    ports:
      - "127.0.0.1:8081:81"
    volumes:
      - ./image-store/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html5up-stellar/:/data/www # Static content
      - ./images/:/data/images
    networks:
      - backend

networks:
  backend:
    driver: bridge
