version: '3.6'
services:

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html5up-stellar/:/var/www/html # Static content
    networks:
      - backend

networks:
  backend:
    driver: bridge
